const STATES = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  WAITING_FOR_PAYMENT: 'WAITING_FOR_PAYMENT',
  PAYMENT_RECONCILING: 'PAYMENT_RECONCILING',
  WAITING_FOR_REVIVE: 'WAITING_FOR_REVIVE',
  COMPLETED: 'COMPLETED',
  FAILED_ATTEMPT_CHOICE: 'FAILED_ATTEMPT_CHOICE',
  RETRY_OFFERED: 'RETRY_OFFERED',
  REFUND_REQUIRED: 'REFUND_REQUIRED',
  REFUND_RECONCILING: 'REFUND_RECONCILING',
  REFUNDED: 'REFUNDED',
  CANCELLED_BY_REQUESTER: 'CANCELLED_BY_REQUESTER',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  CLOSED_REQUESTER_EXIT: 'CLOSED_REQUESTER_EXIT',
  CLOSED_NATURAL_EXPIRY: 'CLOSED_NATURAL_EXPIRY',
  REPORTABLE_NO_ATTEMPT: 'REPORTABLE_NO_ATTEMPT',
  REPORTABLE_MISSING_REFUND: 'REPORTABLE_MISSING_REFUND'
});

const TERMINAL_STATES = new Set([
  STATES.PAYMENT_EXPIRED,
  STATES.COMPLETED,
  STATES.REFUNDED,
  STATES.CANCELLED_BY_REQUESTER,
  STATES.CLOSED_REQUESTER_EXIT,
  STATES.CLOSED_NATURAL_EXPIRY,
  STATES.REPORTABLE_NO_ATTEMPT,
  STATES.REPORTABLE_MISSING_REFUND
]);

const TRANSITIONS = Object.freeze({
  [STATES.AVAILABLE]: Object.freeze({
    accept: STATES.WAITING_FOR_PAYMENT
  }),
  [STATES.WAITING_FOR_PAYMENT]: Object.freeze({
    requester_cancel: STATES.CANCELLED_BY_REQUESTER,
    payment_verified: STATES.WAITING_FOR_REVIVE,
    deadline: STATES.PAYMENT_RECONCILING
  }),
  [STATES.PAYMENT_RECONCILING]: Object.freeze({
    payment_verified: STATES.WAITING_FOR_REVIVE,
    payment_expired: STATES.PAYMENT_EXPIRED,
    late_payment: STATES.REFUND_REQUIRED
  }),
  [STATES.WAITING_FOR_REVIVE]: Object.freeze({
    revive_success: STATES.COMPLETED,
    revive_failed: STATES.FAILED_ATTEMPT_CHOICE,
    third_party_revive: STATES.REFUND_REQUIRED,
    requester_exit: STATES.CLOSED_REQUESTER_EXIT,
    natural_expiry: STATES.CLOSED_NATURAL_EXPIRY,
    no_attempt: STATES.REPORTABLE_NO_ATTEMPT
  }),
  [STATES.FAILED_ATTEMPT_CHOICE]: Object.freeze({
    retry_requested: STATES.RETRY_OFFERED,
    refund_requested: STATES.REFUND_REQUIRED
  }),
  [STATES.RETRY_OFFERED]: Object.freeze({
    retry_accepted: STATES.WAITING_FOR_REVIVE,
    retry_declined: STATES.REFUND_REQUIRED,
    retry_timeout: STATES.REFUND_REQUIRED
  }),
  [STATES.REFUND_REQUIRED]: Object.freeze({
    refund_verified: STATES.REFUNDED,
    deadline: STATES.REFUND_RECONCILING
  }),
  [STATES.REFUND_RECONCILING]: Object.freeze({
    refund_verified: STATES.REFUNDED,
    missing_refund: STATES.REPORTABLE_MISSING_REFUND
  })
});

function canTransition(from, event) {
  const transitions = TRANSITIONS[from];
  if (!transitions) return null;
  return transitions[event] || null;
}

function isTerminalState(state) {
  return TERMINAL_STATES.has(state);
}

module.exports = {
  STATES,
  canTransition,
  isTerminalState
};
