const fs=require('node:fs');
const path=require('node:path');
const cp=require('node:child_process');
const {DIRECT_SUPPORT_MODULES}=require('./client-modules');
const root=path.resolve(__dirname,'..');
const source=path.join(root,'torn-revive-chat-collector.user.js');
const outDir=path.join(root,'dist');
const version=require(path.join(root,'package.json')).version;
const requiredSupportModules=DIRECT_SUPPORT_MODULES;
const RELEASE_CHANNELS=Object.freeze(['review','stable']);

function git(...args){return cp.execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();}
function currentGitCommit(){const commit=git('rev-parse','HEAD');if(!/^[0-9a-f]{40}$/.test(commit))throw new Error('ReviveRelay build requires a 40-hex Git commit');return commit;}
function ensureTimestamp(value){const text=String(value||'');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(text)||Number.isNaN(Date.parse(text)))throw new Error('Invalid ReviveRelay build timestamp');return text;}
function readPinnedBuildManifest(){const manifestPath=path.join(root,'docs','review','BUILD-MANIFEST.json');if(!fs.existsSync(manifestPath))return null;try{return JSON.parse(fs.readFileSync(manifestPath,'utf8'));}catch(_){throw new Error('Invalid pinned build manifest JSON');}}
function resolveBuildIdentity({version:targetVersion=version,headCommit=currentGitCommit(),nowTimestamp=new Date().toISOString(),manifest=readPinnedBuildManifest()}={}){const freshCommit=String(headCommit||'');if(!/^[0-9a-f]{40}$/.test(freshCommit))throw new Error('ReviveRelay build requires a 40-hex Git commit');const freshTimestamp=ensureTimestamp(nowTimestamp);if(!manifest||manifest.version!==targetVersion)return {gitCommit:freshCommit,buildTimestamp:freshTimestamp,pinned:false};const pinnedCommit=String(manifest.artifactSourceCommit||'');const pinnedTimestamp=String(manifest.buildTimestamp||'');if(!/^[0-9a-f]{40}$/.test(pinnedCommit)||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(pinnedTimestamp)||Number.isNaN(Date.parse(pinnedTimestamp)))throw new Error('Invalid pinned build manifest identity');return {gitCommit:pinnedCommit,buildTimestamp:pinnedTimestamp,pinned:true};}
function ensureSource(text){for(const marker of ['__REVIVERELAY_VERSION__','__REVIVERELAY_UPDATE_URL__','__REVIVERELAY_DOWNLOAD_URL__','__REVIVERELAY_UPDATE_CHANNEL__','__REVIVERELAY_GIT_COMMIT__','__REVIVERELAY_BUILD_TIMESTAMP__'])if(!text.includes(marker))throw new Error(`Missing build marker ${marker}`);if(/^\/\/ @require\s+/m.test(text))throw new Error('ReviveRelay release template must not use runtime @require dependencies');}
function splitUserscript(text){const marker='// ==/UserScript==';const end=text.indexOf(marker);if(end<0)throw new Error('Userscript metadata header missing');const metadataEnd=end+marker.length;return {metadata:text.slice(0,metadataEnd),body:text.slice(metadataEnd)};}
function bundledModule(relativePath){const modulePath=path.join(root,relativePath);if(!fs.existsSync(modulePath))throw new Error(`Required userscript support module not found: ${relativePath}`);const content=fs.readFileSync(modulePath,'utf8');const separator=content.endsWith('\n')?'':'\n';return `/* ReviveRelay bundled module: ${relativePath} */\n${content}${separator}/* ReviveRelay end bundled module: ${relativePath} */`;}
function bundleSupportModules(text){const {metadata,body}=splitUserscript(text);const modules=requiredSupportModules.map(bundledModule).join('\n\n');return `${metadata}\n\n${modules}${body}`;}
function channelUrls(channel){if(!RELEASE_CHANNELS.includes(channel))throw new Error('Invalid release channel');const base=`https://reviverelay.voidsmithindustries.com/releases/${channel}/${version}`;return {updateUrl:`${base}/ReviveRelay-${version}.meta.js`,downloadUrl:`${base}/ReviveRelay-${version}.user.js`};}
function variant(sourceText,{channel,gitCommit,buildTimestamp}){const urls=channelUrls(channel);const templated=sourceText.replaceAll('__REVIVERELAY_VERSION__',version).replace('__REVIVERELAY_UPDATE_URL__',urls.updateUrl).replace('__REVIVERELAY_DOWNLOAD_URL__',urls.downloadUrl).replaceAll('__REVIVERELAY_UPDATE_CHANNEL__',channel).replaceAll('__REVIVERELAY_GIT_COMMIT__',gitCommit).replaceAll('__REVIVERELAY_BUILD_TIMESTAMP__',ensureTimestamp(buildTimestamp));if(/__REVIVERELAY_(?:VERSION|UPDATE_URL|DOWNLOAD_URL|UPDATE_CHANNEL|GIT_COMMIT|BUILD_TIMESTAMP)__/.test(templated))throw new Error('Unresolved ReviveRelay build marker');return bundleSupportModules(templated);}
function metadataOnly(text){return `${splitUserscript(text).metadata}\n`;}
function buildChannelArtifact(channel,{gitCommit=currentGitCommit(),buildTimestamp=new Date().toISOString(),write=true}={}){if(!RELEASE_CHANNELS.includes(channel))throw new Error('Invalid release channel');const sourceText=fs.readFileSync(source,'utf8');ensureSource(sourceText);const artifact=variant(sourceText,{channel,gitCommit,buildTimestamp});const meta=metadataOnly(artifact);const channelDir=path.join(outDir,channel);const userPath=path.join(channelDir,`ReviveRelay-${version}.user.js`);const metaPath=path.join(channelDir,`ReviveRelay-${version}.meta.js`);if(write){fs.mkdirSync(channelDir,{recursive:true});fs.writeFileSync(userPath,artifact);fs.writeFileSync(metaPath,meta);}return {channel,version,gitCommit,buildTimestamp,userPath,metaPath,artifact,meta,urls:channelUrls(channel)};}
function main(){if(!fs.existsSync(source))throw new Error('Installable userscript not found.');for(const relativePath of requiredSupportModules)if(!fs.existsSync(path.join(root,relativePath)))throw new Error(`Required userscript support module not found: ${relativePath}`);fs.mkdirSync(outDir,{recursive:true});fs.rmSync(path.join(outDir,'review'),{recursive:true,force:true});fs.rmSync(path.join(outDir,'stable'),{recursive:true,force:true});for(const legacy of ['reviverelay-auto.user.js','reviverelay-auto.meta.js','reviverelay-manual.user.js'])fs.rmSync(path.join(outDir,legacy),{force:true});const identity=resolveBuildIdentity();const result=buildChannelArtifact('review',{gitCommit:identity.gitCommit,buildTimestamp:identity.buildTimestamp});console.log(`Built immutable ReviveRelay ${version} review artifact at ${identity.gitCommit}${identity.pinned?' (reproduced from pinned manifest)':''}`);return result;}
if(require.main===module)main();
module.exports={variant,metadataOnly,ensureSource,currentGitCommit,readPinnedBuildManifest,resolveBuildIdentity,requiredSupportModules,splitUserscript,bundleSupportModules,bundledModule,buildChannelArtifact,channelUrls,RELEASE_CHANNELS,main};
