const fs=require('node:fs'); const path=require('node:path'); const crypto=require('node:crypto'); const cp=require('node:child_process');
const {validateReleaseManifest}=require('../server/src/domain/client-version');
const root=path.resolve(__dirname,'..');
const URLS={autoInstall:'https://reviverelay.voidsmithindustries.com/install/reviverelay-auto.user.js',autoMeta:'https://reviverelay.voidsmithindustries.com/install/reviverelay-auto.meta.js',manualInstall:'https://reviverelay.voidsmithindustries.com/install/reviverelay-manual.user.js'};
function buildReleaseManifest({version,minimumVersion,mandatory=false,releaseNotes,releasedAt,gitCommit,autoSha256,manualSha256}) { return validateReleaseManifest({latestVersion:version,minimumVersion,releasedAt,releaseNotes,gitCommit,automatic:{installUrl:URLS.autoInstall,metaUrl:URLS.autoMeta,sha256:autoSha256},manual:{installUrl:URLS.manualInstall,sha256:manualSha256},mandatory:Boolean(mandatory)}); }
function sha256(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function git(...args){return cp.execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();}
function parseArgs(argv){ const out={mandatory:false}; for(let i=0;i<argv.length;i+=1){ const arg=argv[i]; if(arg==='--mandatory') out.mandatory=true; else if(arg==='--minimum') out.minimumVersion=argv[++i]; else if(arg==='--notes-file') out.notesFile=argv[++i]; else throw new Error(`Unknown argument: ${arg}`); } return out; }
function main(argv=process.argv.slice(2)) { const args=parseArgs(argv); if(!args.minimumVersion) throw new Error('--minimum is required'); if(!args.notesFile) throw new Error('--notes-file is required'); if(git('status','--porcelain')) throw new Error('Release requires a clean Git tree'); const notesPath=path.resolve(args.notesFile); if(!fs.existsSync(notesPath)) throw new Error('Release notes file does not exist'); const releaseNotes=fs.readFileSync(notesPath,'utf8').trim(); if(releaseNotes.length>4000) throw new Error('Release notes exceed 4000 characters'); const pkg=require(path.join(root,'package.json')); const manifest=buildReleaseManifest({version:pkg.version,minimumVersion:args.minimumVersion,mandatory:args.mandatory,releaseNotes,releasedAt:new Date().toISOString(),gitCommit:git('rev-parse','HEAD'),autoSha256:sha256(path.join(root,'dist/reviverelay-auto.user.js')),manualSha256:sha256(path.join(root,'dist/reviverelay-manual.user.js'))}); fs.writeFileSync(path.join(root,'dist/release-manifest.json'),`${JSON.stringify(manifest,null,2)}\n`); console.log(`Built release manifest ${manifest.latestVersion} at ${manifest.gitCommit}`); return manifest; }
if(require.main===module){try{main();}catch(error){console.error(error.message);process.exitCode=1;}}
module.exports={buildReleaseManifest,parseArgs,main};
