(function(root,factory){const api=factory(root&&root.ReviveRelayVersioning);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ReviveRelayUpdateManager=api;})(typeof globalThis!=='undefined'?globalThis:this,function(browserVersioning){
'use strict';
const DAY_MS=86_400_000;
function versioning(){if(browserVersioning)return browserVersioning;if(typeof require==='function')return require('./versioning');throw new Error('ReviveRelay versioning unavailable');}
function clone(value){return value==null?value:JSON.parse(JSON.stringify(value));}
function validateManifest(input,expectedChannel=null){const {compareVersions}=versioning();if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Invalid manifest');for(const key of ['latestVersion','minimumVersion','buildTimestamp','releaseNotes','gitCommit','releaseChannel','sha256','apiCompatibility','install','mandatory'])if(!(key in input))throw new Error('Invalid manifest');compareVersions(input.latestVersion,input.minimumVersion);if(compareVersions(input.minimumVersion,input.latestVersion)>0)throw new Error('Invalid manifest minimum');if(!['review','stable'].includes(input.releaseChannel)||expectedChannel&&input.releaseChannel!==expectedChannel)throw new Error('Invalid manifest channel');if(typeof input.releaseNotes!=='string'||input.releaseNotes.length>4000||typeof input.buildTimestamp!=='string'||Number.isNaN(Date.parse(input.buildTimestamp))||typeof input.gitCommit!=='string'||!/^[0-9a-f]{40}$/.test(input.gitCommit)||typeof input.sha256!=='string'||!/^[0-9a-f]{64}$/.test(input.sha256)||typeof input.mandatory!=='boolean')throw new Error('Invalid manifest');const expectedReleaseBase=`https://reviverelay.voidsmithindustries.com/releases/${input.releaseChannel}/${input.latestVersion}`;if(!input.install||input.install.installUrl!==`${expectedReleaseBase}/ReviveRelay-${input.latestVersion}.user.js`||input.install.metaUrl!==`${expectedReleaseBase}/ReviveRelay-${input.latestVersion}.meta.js`)throw new Error('Invalid manifest');if(!input.apiCompatibility||!Number.isInteger(input.apiCompatibility.minimum)||!Number.isInteger(input.apiCompatibility.current)||input.apiCompatibility.current<input.apiCompatibility.minimum)throw new Error('Invalid manifest');return clone(input);}
function createUpdateManager({currentVersion,channel,fetchManifest,getState,saveState,now=Date.now,openUrl}){const {compareVersions}=versioning();if(!['review','stable'].includes(channel)||typeof fetchManifest!=='function'||typeof getState!=='function'||typeof saveState!=='function'||typeof openUrl!=='function')throw new Error('Update manager dependencies are required');function read(){const value=getState();return value&&typeof value==='object'?clone(value):{};}function write(state){const next={lastCheckedAt:Number(state.lastCheckedAt||0),lastManifest:state.lastManifest?clone(state.lastManifest):null,dismissedVersion:state.dismissedVersion||null};saveState(next);return next;}function describe(manifest,state,extra={}){if(!manifest)return {updateAvailable:false,mandatory:false,supported:true,...extra};const updateAvailable=compareVersions(manifest.latestVersion,currentVersion)>0;const supported=compareVersions(currentVersion,manifest.minimumVersion)>=0;const dismissed=Boolean(updateAvailable&&!manifest.mandatory&&state.dismissedVersion===manifest.latestVersion);return {manifest:clone(manifest),latestVersion:manifest.latestVersion,minimumVersion:manifest.minimumVersion,updateAvailable,mandatory:manifest.mandatory,supported,dismissed,...extra};}async function check({force=false}={}){let state=read();const timestamp=Number(now());if(!force&&state.lastCheckedAt&&timestamp-state.lastCheckedAt<DAY_MS)return describe(state.lastManifest,state,{skipped:true,lastCheckedAt:state.lastCheckedAt});try{const manifest=validateManifest(await fetchManifest(),channel);if(state.dismissedVersion&&state.dismissedVersion!==manifest.latestVersion)state.dismissedVersion=null;state=write({...state,lastCheckedAt:timestamp,lastManifest:manifest});return describe(manifest,state,{skipped:false,lastCheckedAt:timestamp});}catch(_){state=write({...state,lastCheckedAt:timestamp,lastManifest:null});return {error:'INVALID_MANIFEST',updateAvailable:false,mandatory:false,supported:true,skipped:false,lastCheckedAt:timestamp};}}function dismiss(version){let state=read();const manifest=state.lastManifest;if(!manifest||manifest.mandatory||manifest.latestVersion!==version)return false;state=write({...state,dismissedVersion:version});return true;}function openUpdate(){const manifest=read().lastManifest;if(!manifest||manifest.releaseChannel!==channel||!manifest.install?.installUrl)return false;openUrl(manifest.install.installUrl);return true;}return Object.freeze({check,dismiss,openUpdate,getState:read});}
return Object.freeze({DAY_MS,validateManifest,createUpdateManager});
});
